---
title: "nGD comparisons"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "")
print(getwd())
```

# Directories

```{r Defining directories, messages = FALSE}
# Folders
rm(list = ls())
metadata_dir <- "../../Data/Metadata/fertility_meta_with_new_infer_causes_double_causes.csv"
feat_table_dir <- "../../Data/GTDB_sensitive"
prevalence_cutoff = 0.05
avg_abundance_cutoff = 0.05
remove_rare = TRUE
unclassified_threshold = 80
sample_with_n_markers = 8
marker_in_n_samples = 1
n = 2
path = file.path("../../StrainPhlan", paste0("sample_with_n_markers_", sample_with_n_markers, "_marker_in_n_samples_",marker_in_n_samples))
long_path = file.path(path, "ngd_long")
wide_path = file.path(path, "ngd_mat")

res_dir = paste0("../../Results/revised_", as.character(unclassified_threshold), "_unclassif")

save_dir = file.path(res_dir, paste0("ngd_plots_sample_with_n_markers_", sample_with_n_markers, "_marker_in_n_samples_", marker_in_n_samples))
if (!file.exists(save_dir)){
  dir.create(save_dir)
}
```
 
# Libraries

```{r Loading libraries, message = FALSE, warning = FALSE}
# library(tidyverse)
library(readr)
library(ggridges)
library(ggbeeswarm)
library(ggplot2)
library(tibble)
library(tidyr)
library(ape)
library(dplyr)
library(cowplot)
library(vegan)
library(kableExtra)
library(stringr)  
library(data.table)
library(purrr)
library(kableExtra)
library(ggpmisc)
library(ggpubr)
library(fmsb)
library(ggforce)
library(rstatix)
library(colorRamp2)
library(ComplexHeatmap)
library(extrafont)
library(showtext)
font_add_google("Gafata")
showtext_auto()
library(chisq.posthoc.test)
library(vegan)

options(scipen = 999)
source('packages/raw_data_analysis_utils.R')
source('packages/data_manipulations.R')
source('packages/metaphlan_functions.R')
source('packages/load_data.R')
source('packages/strainphlan_res_functions.R')
source('packages/strainphlan_review_additions.R')


cst_colors = c('I' = '#9d0208', 'II' = '#FFD60A', 'III' = '#e85d04', 'IV-A' = '#22577a', 'IV-B' = '#5390D9', 'IV-C' = '#2E214F', 'V' = '#E2D6B8')
community_colors = c('I-A' = '#9d0208', 'I-B' = '#dc2f02', 'II' = '#FFD60A', 'III-A' = '#e85d04','III-B' = '#faa307','IV-A' = '#22577a', 'IV-B' = '#5390D9', 'IV-C0' = '#2E214F', 'IV-C1' = '#63479B','IV-C2' = '#8962C7', 'IV-C3' = '#AB7DDA', 'IV-C4' = '#DEC9E9', 'V' = '#E2D6B8')
organ_colors = c("rectal" = '#FFB703', "vaginal" = '#EB5E00')
parameter_colors = c("0" = "#669BBC", "1" = "#C1121F")
```

# Load composition data

```{r load and order, message = TRUE, warning = FALSE}
meta = order_meta(metadata_dir, feat_table_dir, "valencia_metaphlan_res", FALSE)

metaphlan <- read_tsv2(file.path(feat_table_dir, "metaphlan4_taxonomy_METAPHLAN4.tsv"), cmnt = "#")

t_metaphlan <- reorganize_metaphlan_table(metaphlan, 't')
t_metaphlan_lst <- sep_one_organ_metaphlan(t_metaphlan, rem = TRUE, remove_rare = FALSE, prevalence_cutoff = prevalence_cutoff, avg_abundance_cutoff = avg_abundance_cutoff, remove_unclassified_column = TRUE, unclassified_threshold = unclassified_threshold)

sp_metaphlan <- reorganize_metaphlan_table(metaphlan, 's')
sp_metaphlan_lst <- sep_one_organ_metaphlan(sp_metaphlan, rem = TRUE, remove_rare = FALSE, prevalence_cutoff = prevalence_cutoff, avg_abundance_cutoff = avg_abundance_cutoff, remove_unclassified_column = TRUE, unclassified_threshold = unclassified_threshold)

ge_metaphlan <- reorganize_metaphlan_table(metaphlan, 'g')
ge_metaphlan_lst <- sep_one_organ_metaphlan(ge_metaphlan, rem = TRUE, remove_rare = FALSE, prevalence_cutoff = prevalence_cutoff, avg_abundance_cutoff = avg_abundance_cutoff, remove_unclassified_column = TRUE, unclassified_threshold = unclassified_threshold)

ph_metaphlan <- reorganize_metaphlan_table(metaphlan, 'p')
ph_metaphlan_lst <- sep_one_organ_metaphlan(ge_metaphlan, rem = TRUE, remove_rare = FALSE, prevalence_cutoff = prevalence_cutoff, avg_abundance_cutoff = avg_abundance_cutoff, remove_unclassified_column = TRUE, unclassified_threshold = unclassified_threshold)

metaphlan_lst = list("phylum" = ph_metaphlan_lst, "genus" = ge_metaphlan_lst, "species" = sp_metaphlan_lst, "sgb" = t_metaphlan_lst)

orig_meta = meta
common = Reduce(intersect, list(sp_metaphlan_lst$vaginal$sample_id, sp_metaphlan_lst$rectal$sample_id, meta$sample_id))
meta = meta %>% filter(sample_id %in% common)
for (level in names(metaphlan_lst)){
  lst = metaphlan_lst[[level]]
  for (organ in names(lst)){
    print(paste0("level = ", level, ", organ = ", organ))
    n_samples = df %>% nrow()
    df = lst[[organ]]
    filt_df = df %>% filter(sample_id %in% common)
    filt_n_samples = filt_df %>% nrow()
    message(paste0(filt_n_samples, " samples were filtered from ", n_samples))
    features_filt_df = remove_rare_features(filt_df, filter_method = 'both', prevalence_cutoff = prevalence_cutoff, avg_abundance_cutoff = avg_abundance_cutoff)
    metaphlan_lst[[level]][[organ]] = features_filt_df
  }
}
```

# Load sgb mapping

```{r}
sgb_map_df = read_delim(file.path("../../StrainPhlan/mpa_vJan21_CHOCOPhlAnSGB_202103_SGB2GTDB.tsv"), delim = "\t", show_col_types = FALSE, col_names = FALSE) 
sgb_2_gtdb = sgb_map_df %>%
              rename("sgb" = "X1", "taxonomy" = "X2") %>%
              # mutate(sgb = str_replace(sgb, "_group", "")) %>%
              mutate(taxonomy = str_replace_all(taxonomy, " ", "_")) %>%
              separate_rows(taxonomy, sep = ";") %>% 
              separate(taxonomy, into = c("key", "value"), sep = "__") %>%
              pivot_wider(names_from = key, values_from = value) %>%
                mutate(sgb = paste0("t__", sgb))
```

# Load nGD files

## Load long ngd

```{r}
vaginal_samples = metaphlan_lst$sgb$vaginal$sample_id
rectal_samples = metaphlan_lst$sgb$rectal$sample_id
union_samples = dplyr::union(vaginal_samples, rectal_samples)
```


```{r, message=FALSE}
all_files <- list.files(long_path, recursive = FALSE)
files_only <- file.path(long_path, all_files) 
ngd_lst = list()

for (file_path in files_only){
  name = sub(".*/(.*?)\\_nGD.tsv", "\\1", file_path)
  
  df = read_delim(file_path, delim = "\t", col_names = FALSE, show_col_types = FALSE) %>%
        rename(sample_1 = X1, sample_2 = X2, nGD = X3) %>%
        mutate(sample_1 = str_replace_all(sample_1, c("_CP04600_L001" = "", "CP04600_L00" = "", "_B" = ""))) %>%
        mutate(sample_2 = str_replace_all(sample_2, c("_CP04600_L001" = "", "CP04600_L00" = "", "_B" = ""))) %>%
        mutate(sample_id_1 = str_replace_all(sample_1, "-vaginal|-rectal", "")) %>%
        mutate(sample_id_2 = str_replace_all(sample_2, "-vaginal|-rectal", "")) %>%
        separate(sample_1, into = c("first", "second", "sample_1_organ"), sep = "-", remove = FALSE) %>% select(-c(first, second)) %>%
        separate(sample_2, into = c("first", "second", "sample_2_organ"), sep = "-", remove = FALSE) %>% select(-c(first, second)) %>%
        mutate(same_person = case_when(sample_id_1 == sample_id_2 ~ TRUE, 
                                       sample_id_1 != sample_id_2 ~ FALSE)) %>%
        filter(sample_id_1 %in% union_samples) %>%
        filter(sample_id_2 %in% union_samples) %>%
        mutate(sgb = name) %>%
        left_join(sgb_2_gtdb %>% select(sgb, s), by = "sgb") %>%
        rename("species" = "s")
        
  if (sum(df$same_person, na.rm = TRUE) >= n) { # (name %in% fishers_sgbs){
    ngd_lst[[name]] = df
  }
}
print(length(ngd_lst))
```

## Load wide ngd df

```{r}
all_files <- list.files(wide_path, recursive = FALSE)
files_only <- file.path(wide_path, all_files) 
mat_lst = list()

for (file_path in files_only){
  name = sub(".*/(.*?)\\_nGD_mat.tsv", "\\1", file_path)
  df = read_delim(file_path, delim = "\t", col_names = TRUE, show_col_types = FALSE) %>%
        mutate(ID = str_replace_all(ID, c("_B" = "", "_CP04600_L001" = ""))) %>%
        mutate(ID = str_replace_all(ID, c("_CP04600_L002" = "_2"))) %>%
        rename_with(~ sub("_CP04600_L001", '', .) %>%
                  sub("_B", '', .)) %>%
        rename_with(~ sub("_CP04600_L002", '_2', .))
  mat_lst[[name]] = df
}
```

# Results

## ngd all plot

```{r}
source('../packages/strainphlan_res_functions.R')
ngd_all_lst = get_ngd_violin(ngd_lst, n = n, nrow = 5)
ngd_all_lst$plot = ngd_all_lst$plot +
                    theme(plot.tag = element_text(size = 80, family = "Gafata"))
ggsave(ngd_all_lst[["plot"]], file = file.path(save_dir, paste0("ngd_all_violin_", as.character(n), ".png")), height = 12, width = 15)
```

## PCoA plot

```{r}
pcoa_lst = list()
segment_lst = list()
for (name in names(ngd_lst)){
  # PCoA data
  long_df = ngd_lst[[name]]
  wide_df = mat_lst[[name]]
  ord_long_df = long_df %>%
                filter(sample_1_organ != sample_2_organ) # %>%
  ord_wide_df = wide_df %>%
                
                column_to_rownames("ID")
  dist = as.dist(ord_wide_df)
  pcoa_res = pcoa(dist)
  pcoa_values = pcoa_res$vectors %>%
                  as.data.frame() %>%
                  select(1:2) %>%
                  rownames_to_column("full_sample_id") %>%
                  separate(full_sample_id, into = c("sample_id1", "sample_id2", "organ"), sep = "-", remove = FALSE) %>%
                  mutate(sample_id = paste(sample_id1, sample_id2, sep = "-")) %>%
                  select(-c(sample_id1, sample_id2)) %>%
                  mutate(organ = str_remove(organ, "_2")) %>%
                  rename("PCoA1" = "Axis.1", "PCoA2" = "Axis.2") %>%
                  mutate(species = unique(long_df$species)) %>%
                  mutate(species = str_replace_all(species, "_", " "))
  pcoa_lst[[name]] = pcoa_values
  # Segments data
  label_samples = long_df %>% filter(same_person == TRUE) %>% pull(sample_id_1)
  seg_df = pcoa_values %>% filter(sample_id %in% label_samples) 
  vag_seg_df = seg_df %>% filter(organ == "vaginal") %>% rename("x" = "PCoA1", "y" = "PCoA2")
  rec_seg_df = seg_df %>% filter(organ == "rectal") %>% rename("xend" = "PCoA1", "yend" = "PCoA2")
  full_seg_df = vag_seg_df %>% left_join(rec_seg_df, by = c("sample_id", "species")) %>%
                select(-matches("full_sample_id|organ")) %>%
                select(c(sample_id, x, y, xend, yend, species))
  segment_lst[[name]] = full_seg_df
}
```

```{r}
filter_sgbs = function(df, sgbs){
  filt_df = df %>%
           rownames_to_column("sgb") %>%
           separate(sgb, into = c("sgb", "num"), sep = "\\.") %>%
           select(-c("num")) %>%
           filter(sgb %in% sgbs)
  return(filt_df)
}

pcoa_all = do.call("rbind", pcoa_lst)
segment_all = do.call("rbind", segment_lst)
ngd_for_plot = ngd_all %>%
                as.data.frame() %>%
                group_by(sgb) %>%
                filter(sum(same_person == TRUE) >= n) %>%
                ungroup()
pcoa_all = filter_sgbs(pcoa_all, unique(ngd_for_plot$sgb))
pcoa_all = pcoa_all %>% mutate(species = factor(species, levels = ngd_all_lst$stats_results$species))
segment_all = filter_sgbs(segment_all, unique(ngd_for_plot$sgb))
segment_all = segment_all %>% mutate(species = factor(species, levels = ngd_all_lst$stats_results$species))
```

```{r}
pcoa_all = bind_rows(pcoa_lst, .id = "sgb")
segment_all = bind_rows(segment_lst, .id = "sgb")
labels = c("vaginal" = "Vaginal", "rectal" = "Rectal")
pcoa_plot = get_pcoa_plot(pcoa_all, segment_all, nrow = 3)
ggsave(pcoa_plot, file = file.path(save_dir, "all_samples_pcoa_distances_grey_transparent.png"), height = 7, width = 12, dpi = 300)
```

## Z score Heatmap

```{r}
ngd_long_all = bind_rows(ngd_lst, .id = "sgb") 
save_df_path = file.path(save_dir, paste0("ngd_all_n_", as.character(n), ".csv"))
write.csv(file = save_df_path, ngd_long_all, quote = FALSE, row.names = FALSE)
```

### Non normal P value

```{r}
levels_species_df = ngd_all_lst$stats_results %>%
                    mutate(species = str_replace_all(species, " ", "_"))

ngd_long_all = ngd_long_all %>%
                as.data.frame() %>%
                filter(sample_1_organ != sample_2_organ) %>%
                group_by(sgb) %>%
                filter(sum(same_person == TRUE) >= n) %>%
                ungroup() %>%
                mutate(log_dist = log(nGD)) 

new_stats_between <- ngd_long_all %>%
                  filter(sample_id_1 != sample_id_2) %>%
                  group_by(sgb) %>%
                  summarise(mean_between   = mean(nGD, na.rm = TRUE),
                    sd_between     = sd(nGD, na.rm = TRUE),
                    median_between = median(nGD, na.rm = TRUE),
                    mad_between    = mad(nGD, na.rm = TRUE),
                    .groups = "drop")

normality_test <- ngd_long_all %>%
                    filter(sample_id_1 != sample_id_2) %>%
                    group_by(sgb) %>%
                    filter(n() >= 3) %>%
                    summarise(
                      shapiro_p  = shapiro.test(log_dist)$p.value,
                      n_between  = n(),
                      .groups = "drop"
                    ) %>%
                    mutate(is_normal = shapiro_p > 0.05)

between_vals <- ngd_long_all %>%
                  filter(sample_id_1 != sample_id_2) %>%
                  group_by(sgb) %>%
                  summarise(between_nGD = list(nGD), .groups = "drop")

new_zscore_df = ngd_long_all %>%
              left_join(new_stats_between, by = "sgb") %>%
              left_join(between_vals, by = "sgb") %>%
              mutate(within_sample = sample_id_1 == sample_id_2,
                zscore = if_else(within_sample, (nGD - median_between) / mad_between, NA_real_)) %>% # MAD-based robust z-score instead of mean/sd
              group_by(sgb) %>%
              mutate(pval = if_else(within_sample,
                  map2_dbl(nGD, between_nGD, function(observed, between) {n_perm = 10000
                    perm_draws = sample(between, size = n_perm, replace = TRUE) # one-tailed: looking for unusually LOW values (strain sharing)
                    mean(perm_draws <= observed, na.rm = TRUE)}), NA_real_)) %>%
              ungroup() %>%
              mutate(fdr = p.adjust(pval, method = 'BH')) %>%
              mutate(species = factor(species, levels = levels_species_df$species))

new_order_vector = new_zscore_df %>% 
                arrange(sd_between) %>%
                distinct(species) %>% 
                mutate(species = str_replace_all(species, "_", " ")) %>%
                pull(species)
```


### Normal P value

```{r}
levels_species_df = ngd_all_lst$stats_results %>%
                    mutate(species = str_replace_all(species, " ", "_"))
ngd_long_all = ngd_long_all %>%
                as.data.frame() %>%
                filter(sample_1_organ != sample_2_organ) %>%
                group_by(sgb) %>%
                filter(sum(same_person == TRUE) >= n) %>%
                ungroup()  
stats_between <- ngd_long_all %>%
                  filter(sample_id_1 != sample_id_2) %>%
                  group_by(sgb) %>%
                  summarise(mean_between = mean(nGD, na.rm = TRUE),
                  sd_between = sd(nGD, na.rm = TRUE), .groups = "drop")
zscore_df = ngd_long_all %>%
              left_join(stats_between, by = "sgb") %>%
              mutate(within_sample = sample_id_1 == sample_id_2,
                     zscore = if_else(within_sample, (nGD - mean_between) / sd_between, NA_real_)) %>%
              group_by(sgb) %>%
              mutate(pval = pnorm(zscore, mean = 0, sd = 1, lower.tail = TRUE)) %>%
              ungroup(sgb) %>%
              mutate(fdr = p.adjust(pval, method = 'BH')) %>%
              mutate(species = factor(species, levels = levels_species_df$species))
order_vector = zscore_df %>% 
                arrange(sd_between) %>%
                distinct(species) %>% 
                mutate(species = str_replace_all(species, "_", " ")) %>% pull(species)
```

```{r}
levels_species = ngd_all_lst$stats_results %>%
                    arrange(p.adj) %>% pull(species)
tile_df = zscore_df %>%
          mutate(species = str_replace_all(species, "_", " ")) %>%
          filter(sample_1_organ != sample_2_organ) %>%
          filter(same_person == TRUE) %>%
          select(c(sample_id_1, species, zscore, fdr)) %>%
          mutate(species = factor(species, levels = rev(levels_species))) %>%
          arrange(species) %>%
          mutate(signif = case_when(fdr <= 0.001 ~ "***",
                                              fdr <= 0.01 ~ "**",
                                              fdr <= 0.05 ~ "*",
                                              TRUE ~ ""))

t_plot = get_tile_heatmap(tile_df, breaks_vec = c(-5.8, -2, 0, 0.5, 1)) 
ggsave(t_plot, file = file.path(save_dir, "tiled_plot.png"), width = 10, height = 6)
```


```{r}
sup_df = new_zscore_df %>%
        filter(sample_id_1 == sample_id_2) %>% 
        select(sample_1, species, median_between, mean_between, sd_between, nGD, pval, fdr) %>%
        mutate(pval = round(pval, 3), fdr = round(fdr, 3), mean_between = round(mean_between, 3), sd_between = round(sd_between, 3), median_between = round(median_between, 3), nGD = round(nGD, 3)) %>%
        rename(`Non-parametric P value` = pval, `Non-parameteric FDR-corrected P` = fdr) %>%
        left_join(zscore_df %>% filter(sample_id_1 == sample_id_2) %>% 
        select(sample_1, species, pval, fdr)) %>%
        mutate(pval = round(pval, 3), fdr = round(fdr, 3)) %>%
        rename(`Normal P value` = pval, `Normal FDR-corrected P` = fdr) %>%
        mutate(`Non-parametric significant` = if_else(`Non-parameteric FDR-corrected P` <= 0.05, "Significant", "-")) %>%
        mutate(`Normal significant` = if_else(`Normal FDR-corrected P` <= 0.05, "Significant", "-")) %>%
        mutate(sample_1 = str_replace(sample_1, "^(([^-]+-){1}[^-]+)-.*$", "\\1"), species = str_replace_all(species, "_", " ")) %>%
        rename("Sample ID" = "sample_1", "Species" = "species") %>%
        rename_with(~ str_to_title(str_replace_all(.x, "_", " "))) %>%
        rename("nGD" = "Ngd")

write.csv(file = file.path(save_dir, "sup_z_score_both_ways.csv"), x = sup_df %>% arrange(`Normal Fdr-Corrected P`, Species))
```

```{r}
cols = c("sample_1", "sample_1_organ", "sample_2", "sample_2_organ", "nGD", "same_person", "sgb", "species", "pval", "fdr")
new_test = new_zscore_df %>% 
            select(cols) %>% 
            rename(perm_pval = pval, perm_fdr = fdr) %>%
            mutate(perm_sig = ifelse(perm_fdr <= 0.05, "sig", "not_sig"))
write.csv(file = file.path(save_dir, "new_perm_pvals_zscore.csv"), x = new_test %>% arrange(perm_fdr, species))
test = zscore_df %>% 
        select(cols) %>% 
        mutate(sig = ifelse(fdr <= 0.05, "sig", "not_sig")) %>%
        left_join(new_test) 
test %>% filter(sig != perm_sig) %>% select(c("sample_1", "sample_2", "species", "fdr", "perm_fdr", "sig", "perm_sig"))
```

# Together fig 3

```{r}
all_patched = free(ngd_all_lst$plot / t_plot, type = "label") +
                plot_annotation(tag_levels = "A") +
                theme(plot.tag = element_text(size = 80))
ggsave(file.path(save_dir, "zscore_aes_figure_3.png"), all_patched, height = 14, width = 16, dpi = 300)
```

# Review additions

## Abundance plot

```{r}
source('packages/strainphlan_review_additions.R')
source('packages/maaslin_only.R')

abundance_lst = get_abundance_plot(df_lst = metaphlan_lst$sgb, res_df = ngd_all_lst$stats_results, sgb_2_gtdb, res_dir)
ggsave(abundance_lst$plot, 
       file   = file.path(save_dir, "maaslin_paired_abundance_plot.png"), 
       height = 9, width  = 14.8, dpi = 300)
```

## nGD 1st percentile

```{r}
source('../packages/strainphlan_review_additions.R')
full_percent_df = get_percentile(ngd_all, percentile = 0.01, n = n)
full_percent_df %>% 
  select(species, sample_1, sample_2, same_person, percentile_nGD, sig) %>% 
  filter(same_person == TRUE) %>% arrange(percentile_nGD, sig)
full_percent_df %>% 
  filter(same_person == TRUE) %>% 
  group_by(species, sig) %>% 
  count() %>% 
  left_join(ngd_all_lst$stats_results %>% select(c(s, signif)), by = c("species" = "s")) %>%
  arrange(signif, species, sig, n) %>%
  filter((signif == "ns" & sig == "shared") | (signif != "ns" & sig == "not_shared"))
```

## nGD threshold = 0.005

```{r}
thresh = 0.005
ngd_all %>% 
  filter(same_person == TRUE) %>% 
  mutate(sig = if_else((same_person == TRUE & nGD <= thresh), "shared", "not_shared")) %>%
  group_by(species, sig) %>% 
  count() %>% 
  left_join(ngd_all_lst$stats_results %>% select(c(s, signif)), by = c("species" = "s")) %>%
  arrange(signif, species, sig, n) %>%
  filter((signif == "ns" & sig == "shared") | (signif != "ns" & sig == "not_shared"))
```






